### ISSUE TITLE
Fix issue of logger crashing after some time

### ISSUE THREAD

**Issue by Gertdor** [gtcodes/time_logger_joker#21]
fix cannot fetch data issue

**Comment by Mupperry** [comment]
This seems to be caused by the connection to the database timing-out, which is enabled by default in (most) MySQL implementations, where it is set to 8 hours. A resonable fix would be to try to reconnect if the query fails. See [this.](https://www.percona.com/blog/2010/05/05/checking-for-a-live-database-connection-considered-harmful/)

**Comment by Criticalstone** [comment]
Wow! Great job finding this out!
